### PR TITLE
Add Strongswan 5.6+ support

### PR DESCRIPTION
**Pull request by jhershbe**
meta-measured strongswan bbappend has been broken since sumo moved to version 5.5.

Fix the incompatible options.

### CODE REVIEW

**Comment by amstewart** [comment]
I assume these changes will break compilation in Strongswan<5.6; right? In that case, can you add a commit to rename the bbappend to `_5.6.%.bbappend` or similar?

**Comment by jhershbe** [comment]
I don't see a mechanism to match a range of versions. This doesn't apply specifically to 5.6. One patch is to support 5.5 and beyond. The other is to support 5.6 and beyond.

Looking at the history of this repo, the maintainer always just changed the name to match the version that was current, until 5.3.0 (when the layer it appends was still on 5.2.1) he moved to the 5.% wildcard.

However, in the Sumo branch and the Dunfell branch, the strongswan version is 5.6 or greater.

If I were to name this _5.6.%.bbappend, it would still be broken for Dunfell because the 5.9 version that it has would choose the _5.%.bbappend, which is the current (broken) recipe.

meta-measured has never seemed to support strongswan well (last update to this recipe is 6 years ago?) and simply changing the recipe to support the current version in the lower layer matches the approach taken in all former patches to this bbappend. I welcome a solution that actually allows support for a range of versions, but bitbake appears too limited for that based on what I was able to find.

I would also welcome a way to configure our image build to not apply the bbappend from meta-measured for this recipe.

**Comment by amstewart** [comment]
I see. Probably the most-correct solution would be to move the common code to an includes file, like `strongswan_5.inc` and then to have more-specifically-versioned .bbappends which add support for the changing configurations. But it sounds like that is more work than is worthwhile for both our level of support, and meta-measured's. So I'm OK using a `5.%` wildcard.

One other question though: is it apparent why there are so many `PACKAGECONFIG` operations in the bbappend, which haven't been upstreamed to the meta-oe layer? Are these meta-measured-specific, or is it just a function of no-one seriously touching this recipe in years?

**Comment by jhershbe** [comment]
There is a lot missing from the PACKAGECONFIG operations. It seems the meta-oe layer doesn't include any of the switches for various tpm integration, so meta-measured just defines them there. A lot of this might be simpler if the flags lived in meta-oe and meta-measured just enabled some. Since meta-oe always just supports a single specific version. It's room for improvement and it seems noone is giving it much love for the moment.

**Review by amstewart — APPROVED** [review]

**Pull request merged**
